<?php

namespace Database\Seeders;

use App\Models\Task;
use Illuminate\Database\Seeder;
use Lar\LteAdmin\Core\ModelSaver;

class TasksSeeder extends Seeder
{
    /**
     * @var array
     */
    protected array $data = [
        // Sport
        [
            'direction_id' => 2,
            'name' => 'Челлендж месяца',
            'short_description' => 'Прислать видео (по одному видео каждую пятницу)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-17',
            'finish_at' => '2021-09-17',
            'is_challenge' => 1,
        ],
        [
            'direction_id' => 2,
            'name' => 'Челлендж месяца',
            'short_description' => 'Прислать видео (по одному видео каждую пятницу)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-24',
            'finish_at' => '2021-09-24',
            'is_challenge' => 1,
        ],
        [
            'direction_id' => 2,
            'name' => 'Челлендж месяца',
            'short_description' => 'Прислать видео (по одному видео каждую пятницу)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-10-01',
            'finish_at' => '2021-10-01',
            'is_challenge' => 1,
        ],
        [
            'direction_id' => 2,
            'name' => 'Челлендж месяца',
            'short_description' => 'Прислать видео (по одному видео каждую пятницу)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-10-08',
            'finish_at' => '2021-10-08',
            'is_challenge' => 1,
        ],
        [
            'direction_id' => 2,
            'name' => 'В отличной форме',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-13',
            'finish_at' => '2021-09-13',
        ],
        [
            'direction_id' => 2,
            'name' => 'Игра головой',
            'short_description' => 'Ответить на вопросы викторины',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_QUIZ,
            'start_at' => '2021-09-14',
            'finish_at' => '2021-09-14',
        ],
        [
            'direction_id' => 2,
            'name' => 'Будь в балансе',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-14',
            'finish_at' => '2021-09-16',
        ],
        [
            'direction_id' => 2,
            'name' => 'Качалка',
            'short_description' => 'Скачать файл',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_DOWNLOAD_FILE,
            'action_type' => Task::ACTION_TYPE_AUTO,
            'start_at' => '2021-09-15',
            'finish_at' => '2021-09-15',
        ],
        [
            'direction_id' => 2,
            'name' => 'Стань легендой',
            'short_description' => 'Прислать фото (две фотографии за раз)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-16',
            'finish_at' => '2021-09-16',
        ],
        [
            'direction_id' => 2,
            'name' => 'Кто ты из великих?',
            'short_description' => 'Пройти тест',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_STAR_QUIZ,
            'start_at' => '2021-09-16',
            'finish_at' => '2021-09-16',
        ],
        [
            'direction_id' => 2,
            'name' => 'Конкурс спортивных кричалок',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-17',
            'finish_at' => '2021-09-17',
        ],
        [
            'direction_id' => 2,
            'name' => '20 лет побед',
            'short_description' => 'Ответить на вопросы викторины',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_QUIZ,
            'start_at' => '2021-09-20',
            'finish_at' => '2021-09-20',
        ],
        [
            'direction_id' => 2,
            'name' => 'В "десятку"',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-20',
            'finish_at' => '2021-09-20',
        ],
        [
            'direction_id' => 2,
            'name' => 'Передышка',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-21',
            'finish_at' => '2021-09-21',
        ],
        [
            'direction_id' => 2,
            'name' => 'Разряд по кинопоиску',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-22',
            'finish_at' => '2021-09-22',
        ],
        [
            'direction_id' => 2,
            'name' => 'Бодрое утро',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-22',
            'finish_at' => '2021-09-24',
        ],
        [
            'direction_id' => 2,
            'name' => 'Спортивное ориентирование... в интернете',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-23',
            'finish_at' => '2021-09-23',
        ],
        [
            'direction_id' => 2,
            'name' => 'Не ленись, отожмись',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-24',
            'finish_at' => '2021-09-28',
        ],
        [
            'direction_id' => 2,
            'name' => '#чисточеллендж',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-24',
            'finish_at' => '2021-09-24',
        ],
        [
            'direction_id' => 2,
            'name' => 'Мелодия победы',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-27',
            'finish_at' => '2021-09-27',
        ],
        [
            'direction_id' => 2,
            'name' => 'Фанаты "Деловых Линий"',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-28',
            'finish_at' => '2021-09-30',
        ],
        [
            'direction_id' => 2,
            'name' => 'Новый взгляд на спорт',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-28',
            'finish_at' => '2021-09-28',
        ],
        [
            'direction_id' => 2,
            'name' => 'Властелины колец',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-29',
            'finish_at' => '2021-09-29',
        ],
        [
            'direction_id' => 2,
            'name' => 'Команда мечты',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-30',
            'finish_at' => '2021-10-05',
        ],
        [
            'direction_id' => 2,
            'name' => 'О спорт, ты смех',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-30',
            'finish_at' => '2021-09-30',
        ],
        [
            'direction_id' => 2,
            'name' => 'Все на стадион!',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-10-01',
            'finish_at' => '2021-10-01',
        ],
        [
            'direction_id' => 2,
            'name' => 'Лайфхак чемпиона',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-10-04',
            'finish_at' => '2021-10-04',
        ],
        [
            'direction_id' => 2,
            'name' => 'Набивалити',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-10-05',
            'finish_at' => '2021-10-07',
        ],
        [
            'direction_id' => 2,
            'name' => 'Наши рекорды',
            'short_description' => 'Ответить на вопросы викторины',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_QUIZ,
            'start_at' => '2021-10-05',
            'finish_at' => '2021-10-05',
        ],
        [
            'direction_id' => 2,
            'name' => 'Bottle flip challenge',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-10-06',
            'finish_at' => '2021-10-06',
        ],
        [
            'direction_id' => 2,
            'name' => 'Внимание на экран',
            'short_description' => 'Посмотреть видео, Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-10-07',
            'finish_at' => '2021-10-07',
        ],
        [
            'direction_id' => 2,
            'name' => 'Рецепт победы',
            'short_description' => 'Скачать файл, Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_DOWNLOAD_FILE_PHOTO,
            'start_at' => '2021-10-07',
            'finish_at' => '2021-10-07',
        ],
        [
            'direction_id' => 2,
            'name' => 'Я могу вот так, wow!',
            'short_description' => 'Прислать фото или видео',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE_OR_VIDEO,
            'start_at' => '2021-10-08',
            'finish_at' => '2021-10-08',
        ],
        // Fun
        [
            'direction_id' => 1,
            'name' => 'Челлендж месяца',
            'short_description' => 'Прислать фото (по одному видео каждую пятницу)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-17',
            'finish_at' => '2021-09-17',
            'is_challenge' => 1,
        ],
        [
            'direction_id' => 1,
            'name' => 'Челлендж месяца',
            'short_description' => 'Прислать фото (по одному видео каждую пятницу)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-24',
            'finish_at' => '2021-09-24',
            'is_challenge' => 1,
        ],
        [
            'direction_id' => 1,
            'name' => 'Челлендж месяца',
            'short_description' => 'Прислать фото (по одному видео каждую пятницу)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-10-01',
            'finish_at' => '2021-10-01',
            'is_challenge' => 1,
        ],
        [
            'direction_id' => 1,
            'name' => 'Челлендж месяца',
            'short_description' => 'Прислать фото (по одному видео каждую пятницу)',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-10-08',
            'finish_at' => '2021-10-08',
            'is_challenge' => 1,
        ],
        [
            'direction_id' => 1,
            'name' => '20 лед назад',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-13',
            'finish_at' => '2021-09-13',
        ],
        [
            'direction_id' => 1,
            'name' => 'Бренд-амбассадор',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-14',
            'finish_at' => '2021-09-14',
        ],
        [
            'direction_id' => 1,
            'name' => 'Песня года',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-14',
            'finish_at' => '2021-09-16',
        ],
        [
            'direction_id' => 1,
            'name' => 'О да, еда!',
            'short_description' => 'Прислать фото, Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT_OR_IMAGE,
            'start_at' => '2021-09-15',
            'finish_at' => '2021-09-15',
        ],
        [
            'direction_id' => 1,
            'name' => 'На стиле... фирменном стиле',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-16',
            'finish_at' => '2021-09-20',
        ],
        [
            'direction_id' => 1,
            'name' => 'Орёл и решка',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-16',
            'finish_at' => '2021-09-16',
        ],
        [
            'direction_id' => 1,
            'name' => 'Эмодзи-караоке',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-17',
            'finish_at' => '2021-09-17',
        ],
        [
            'direction_id' => 1,
            'name' => 'Коробка-подарок',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-20',
            'finish_at' => '2021-09-20',
        ],
        [
            'direction_id' => 1,
            'name' => 'Happy birthday, ДЛ!',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-20',
            'finish_at' => '2021-09-22',
        ],
        [
            'direction_id' => 1,
            'name' => 'Эрудиция vs Интуиция',
            'short_description' => 'Ответить на вопросы викторины',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_QUIZ,
            'start_at' => '2021-09-21',
            'finish_at' => '2021-09-21',
        ],
        [
            'direction_id' => 1,
            'name' => 'Книга - лучший подарок',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-22',
            'finish_at' => '2021-09-22',
        ],
        [
            'direction_id' => 1,
            'name' => 'В рабочем режиме',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-22',
            'finish_at' => '2021-09-24',
        ],
        [
            'direction_id' => 1,
            'name' => 'Почта “Деловых Линий”',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-23',
            'finish_at' => '2021-09-23',
        ],
        [
            'direction_id' => 1,
            'name' => 'Город ждёт тебя',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-24',
            'finish_at' => '2021-09-28',
        ],
        [
            'direction_id' => 1,
            'name' => 'Сам себе Лебедев',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-24',
            'finish_at' => '2021-09-24',
        ],
        [
            'direction_id' => 1,
            'name' => 'Ну я вам покажу!',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-27',
            'finish_at' => '2021-09-27',
        ],
        [
            'direction_id' => 1,
            'name' => 'Сколько нас? Двадцать!',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-28',
            'finish_at' => '2021-09-30',
        ],
        [
            'direction_id' => 1,
            'name' => 'В каждом есть немного от Ванги',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-28',
            'finish_at' => '2021-09-28',
        ],
        [
            'direction_id' => 1,
            'name' => 'Давайте дружить треками!',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-29',
            'finish_at' => '2021-09-29',
        ],
        [
            'direction_id' => 1,
            'name' => 'Скороговоркинг',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-09-30',
            'finish_at' => '2021-10-05',
        ],
        [
            'direction_id' => 1,
            'name' => 'Пение под настроение',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-30',
            'finish_at' => '2021-09-30',
        ],
        [
            'direction_id' => 1,
            'name' => 'Маршмеллоу-челлендж',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-10-01',
            'finish_at' => '2021-10-01',
        ],
        [
            'direction_id' => 1,
            'name' => 'Битва уикендов',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-10-04',
            'finish_at' => '2021-10-04',
        ],
        [
            'direction_id' => 1,
            'name' => 'За юбилей!',
            'short_description' => 'Прислать видео',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_VIDEO,
            'start_at' => '2021-10-05',
            'finish_at' => '2021-10-07',
        ],
        [
            'direction_id' => 1,
            'name' => 'Магия числа 20',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-10-05',
            'finish_at' => '2021-10-07',
        ],
        [
            'direction_id' => 1,
            'name' => 'Музыкальная пауза',
            'short_description' => 'Ответить на вопросы викторины',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_QUIZ,
            'start_at' => '2021-10-06',
            'finish_at' => '2021-10-06',
        ],
        [
            'direction_id' => 1,
            'name' => 'Трое деловых',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-10-07',
            'finish_at' => '2021-10-07',
        ],
        [
            'direction_id' => 1,
            'name' => 'Праздничный торт',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-10-07',
            'finish_at' => '2021-10-08',
        ],
        [
            'direction_id' => 1,
            'name' => '20 лет = 20 слов',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-10-08',
            'finish_at' => '2021-10-08',
        ],
        // Funs
        [
            'direction_id' => 3,
            'name' => '#smilechallenge',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-09-13',
            'finish_at' => '2021-09-13',
        ],
        [
            'direction_id' => 3,
            'name' => 'Я - твой фанат',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-16',
            'finish_at' => '2021-09-16',
        ],
        [
            'direction_id' => 3,
            'name' => 'Шестое чувство',
            'short_description' => 'Ответить на вопросы викторины',
            'event_type' => Task::EVENT_TYPE_INSTANT,
            'report_type' => Task::REPORT_TYPE_QUIZ,
            'start_at' => '2021-09-21',
            'finish_at' => '2021-09-21',
        ],
        [
            'direction_id' => 3,
            'name' => 'Дружеское тепло',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-24',
            'finish_at' => '2021-09-24',
        ],
        [
            'direction_id' => 3,
            'name' => 'Вопрос на миллион',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-27',
            'finish_at' => '2021-09-27',
        ],
        [
            'direction_id' => 3,
            'name' => 'Идеальный коллега',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-09-29',
            'finish_at' => '2021-09-29',
        ],
        [
            'direction_id' => 3,
            'name' => 'Фанаты с вами',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-10-01',
            'finish_at' => '2021-10-01',
        ],
        [
            'direction_id' => 3,
            'name' => '#болеемвместе',
            'short_description' => 'Прислать фото',
            'event_type' => Task::EVENT_TYPE_MULTI_DAY,
            'report_type' => Task::REPORT_TYPE_IMAGE,
            'start_at' => '2021-10-04',
            'finish_at' => '2021-10-06',
        ],
        [
            'direction_id' => 3,
            'name' => 'Сам себе DJ',
            'short_description' => 'Прислать текстовое сообщение',
            'event_type' => Task::EVENT_TYPE_ONE_DAY,
            'report_type' => Task::REPORT_TYPE_TEXT,
            'start_at' => '2021-10-07',
            'finish_at' => '2021-10-07',
        ],
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ModelSaver::doMany(Task::class, $this->data);
    }
}
